Allowed periscope materials:
  - nether_brick_fence
  - iron_bars
  - cobblestone_wall

Min periscope height: -1
Max periscope height: -1
Periscope sign text: 'ยง3Periscope'
Periscope create cost: 1000.0