Allowed periscope materials:
  - nether_fence
  - iron_fence
  - cobble_wall
Periscope passthrough blocks: #Blocks that periscopes can "pass through", but cannot make up a significant percentage of a periscope
  nether_brick: 20.0
Allowed commands on periscopes:
  - cruise
  - contacts
Min periscope height: -1
Max periscope height: -1
Periscope sign text: 'ยง3Periscope'
Periscope create cost: 1000.0