name: Periscopes
main: io.github.eirikh1996.periscopes.Periscopes
version: ${project.version}
api-version: '1.16'
softdepend:
  - Movecraft
  - QualityArmory
  - CrackShot
  - Vault
commands:
  periscopes:
    description: Plugin main command
